# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    io_and_status_controller:
      type: ur_controllers/GPIOController


    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster


    force_torque_sensor_broadcaster:
      type: ur_controllers/ForceTorqueStateBroadcaster


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController


    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


    forward_position_controller:
      type: position_controllers/JointGroupPositionController


    gripper_position_controller:
      type: position_controllers/GripperActionController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ur_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

io_and_status_controller:
  ros__parameters:
    joints:
      []
speed_scaling_state_broadcaster:
  ros__parameters:
    joints:
      []
force_torque_sensor_broadcaster:
  ros__parameters:
    joints:
      []
joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []
scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
forward_velocity_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
forward_position_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
gripper_position_controller:
  ros__parameters:
    joint: finger_joint
gripper_controller:
  ros__parameters:
    joints:
      - finger_joint
    command_interfaces:
      []
    state_interfaces:
      []
ur_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []